"""Single source of truth for the ML feature projection (#145).

See ``docs/superpowers/plans/2026-05-19-issue-145-feature-projection.md`` for
the architectural rationale. In short: the same FeatureRow is computed by
three code paths (Python streaming via ``compute_features``, live daemon via
``LiveHistoryProvider``, DuckDB batch via ``_final_join_to_v2``). This module
holds the canonical definitions and is consumed by all three.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Literal

from pscanner.corpus.features import (
    MarketMetadata,
    MarketState,
    Trade,
    WalletState,
)

# Magic numbers. Both engines import these; never inline a literal that
# duplicates one of these.
CONFIDENCE_N_MIN = 20
HIGH_QUALITY_WIN_RATE_THRESHOLD = 0.55
RECENT_TRADES_WINDOW_DAYS = 30
SECONDS_PER_DAY = 86_400
MIN_PRICES_FOR_VOLATILITY = 2

# Multi-label category universe. The DuckDB engine refuses to start if a
# corpus row has a category outside this tuple (see _duckdb_engine.py
# _assert_no_unknown_categories); the registry's cat_* indicators are
# generated by looping over this tuple.
KNOWN_CATEGORIES: tuple[str, ...] = (
    "sports",
    "esports",
    "thesis",
    "macro",
    "elections",
    "crypto",
    "geopolitics",
    "tech",
    "culture",
)

FeatureDType = Literal["float", "int", "str", "tuple_str"]


@dataclass(frozen=True, slots=True)
class FeatureInputs:
    """Bundle of state passed to a feature's Python evaluator.

    ``wallet`` and ``market`` are point-in-time-correct (computed strictly
    from events with ``ts < trade.ts`` by the caller). ``meta`` is static
    per market. ``trade`` is the current row being projected.
    """

    wallet: WalletState
    market: MarketState
    meta: MarketMetadata
    trade: Trade


@dataclass(frozen=True, slots=True)
class FeatureFormula:
    """One column in ``training_examples_v2``.

    ``py`` and ``sql`` MUST compute the same value on the same input. The
    parity test in ``tests/corpus/test_feature_projection_parity.py``
    asserts this with Hypothesis.

    The ``sql`` string is a template — placeholders of the form
    ``{w.field}``, ``{m.field}``, ``{meta.field}``, ``{t.field}`` are
    replaced by ``render_sql_fragment`` using ``SQL_BINDINGS`` below.
    """

    name: str
    dtype: FeatureDType
    nullable: bool
    py: Callable[[FeatureInputs], object]
    sql: str
    docs: str = ""
