"""Single source of truth for the ML feature projection (#145).

See ``docs/superpowers/plans/2026-05-19-issue-145-feature-projection.md`` for
the architectural rationale. In short: the same FeatureRow is computed by
three code paths (Python streaming via ``compute_features``, live daemon via
``LiveHistoryProvider``, DuckDB batch via ``_final_join_to_v2``). This module
holds the canonical definitions and is consumed by all three.
"""

from __future__ import annotations

from collections.abc import Callable, Mapping
from dataclasses import dataclass
from typing import Literal

from pscanner.corpus.features import (
    FeatureRow,
    MarketMetadata,
    MarketState,
    Trade,
    WalletState,
)

# Magic numbers. Both engines import these; never inline a literal that
# duplicates one of these.
CONFIDENCE_N_MIN = 20
HIGH_QUALITY_WIN_RATE_THRESHOLD = 0.55
RECENT_TRADES_WINDOW_DAYS = 30
SECONDS_PER_DAY = 86_400
MIN_PRICES_FOR_VOLATILITY = 2

# Multi-label category universe. The DuckDB engine refuses to start if a
# corpus row has a category outside this tuple (see _duckdb_engine.py
# _assert_no_unknown_categories); the registry's cat_* indicators are
# generated by looping over this tuple.
KNOWN_CATEGORIES: tuple[str, ...] = (
    "sports",
    "esports",
    "thesis",
    "macro",
    "elections",
    "crypto",
    "geopolitics",
    "tech",
    "culture",
)

FeatureDType = Literal["float", "int", "str", "tuple_str"]


@dataclass(frozen=True, slots=True)
class FeatureInputs:
    """Bundle of state passed to a feature's Python evaluator.

    ``wallet`` and ``market`` are point-in-time-correct (computed strictly
    from events with ``ts < trade.ts`` by the caller). ``meta`` is static
    per market. ``trade`` is the current row being projected.
    """

    wallet: WalletState
    market: MarketState
    meta: MarketMetadata
    trade: Trade


@dataclass(frozen=True, slots=True)
class FeatureFormula:
    """One column in ``training_examples_v2``.

    ``py`` and ``sql`` MUST compute the same value on the same input. The
    parity test in ``tests/corpus/test_feature_projection_parity.py``
    asserts this with Hypothesis.

    The ``sql`` string is a template — placeholders of the form
    ``{w.field}``, ``{m.field}``, ``{meta.field}``, ``{t.field}`` are
    replaced by ``render_sql_fragment`` using ``SQL_BINDINGS`` below.
    """

    name: str
    dtype: FeatureDType
    nullable: bool
    py: Callable[[FeatureInputs], object]
    sql: str
    docs: str = ""


# Maps {scope.field} placeholder keys to the SQL column references used by
# pscanner.corpus._duckdb_engine._final_join_to_v2. The names on the SQL
# side are the column aliases that wallet_aggs (wa), market_aggs (ma), and
# wallet_cat_summary (wcs) expose at the final-join stage.
#
# Key naming: "<scope>.<feature-py-attr>". The same logical field can have
# a different name on each engine (e.g. WalletState.cumulative_buy_count
# == wallet_aggs.bet_size_count_w by construction); the binding hides
# that asymmetry.
SQL_BINDINGS: Mapping[str, str] = {
    # WalletState fields
    "w.prior_trades_count": "wa.prior_trades_count_w",
    "w.prior_buys_count": "wa.prior_buys_count_w",
    "w.prior_resolved_buys": "wa.prior_resolved_buys_w",
    "w.prior_wins": "wa.prior_wins_w",
    "w.prior_losses": "wa.prior_losses_w",
    "w.cumulative_buy_price_sum": "wa.cum_buy_price_sum_w",
    # WalletState.cumulative_buy_count tracks the same count as bet_size_count
    # by construction; the SQL side uses the bet_size_count_w column for both.
    "w.cumulative_buy_count": "wa.bet_size_count_w",
    "w.bet_size_sum": "wa.bet_size_sum_w",
    "w.bet_size_count": "wa.bet_size_count_w",
    "w.realized_pnl_usd": "wa.prior_realized_pnl_usd_w",
    "w.last_trade_ts": "wa.last_trade_ts_w",
    "w.first_seen_ts": "wa.first_seen_ts",
    "w.prior_trades_30d": "wa.prior_trades_30d_w",
    # MarketState fields
    "m.volume_so_far_usd": "ma.market_volume_so_far_w",
    "m.unique_traders_count": "ma.market_unique_traders_so_far_w",
    "m.market_age_start_ts": "ma.market_first_prior_ts_w",
    "m.last_trade_price": "ma.last_trade_price_w",
    "m.price_volatility": "ma.price_volatility_w",
    "m.price_count_20": "ma.price_count_20",
    # MarketMetadata fields
    "meta.category": "wa.category",
    "meta.categories_json": "wa.categories_json",
    "meta.closed_at": "wa.closed_at",
    # Trade fields (the current row being projected)
    "t.notional_usd": "wa.notional_usd",
    "t.price": "wa.price",
    "t.outcome_side": "wa.outcome_side",
    "t.ts": "wa.event_ts",
    # Already-computed columns (from wallet_cat_summary subquery)
    "wcs.top_category": "wcs.top_category",
    "wcs.category_diversity": "COALESCE(wcs.category_diversity, 0)",
}


def render_sql_fragment(template: str, bindings: Mapping[str, str] = SQL_BINDINGS) -> str:
    """Resolve ``{scope.field}`` placeholders against ``bindings``.

    Raises ``KeyError`` if the template references an unbound placeholder
    (e.g. ``{w.bogus_field}``) — this catches typos at module-load time
    instead of producing malformed SQL at query time.
    """
    rendered = template
    for key, value in bindings.items():
        rendered = rendered.replace("{" + key + "}", value)
    # Belt-and-braces: if any "{...}" placeholder survives the loop, it
    # didn't match a binding key. Surface that as a clear error rather
    # than letting DuckDB choke on the literal braces.
    if "{" in rendered:
        # Find the first unresolved placeholder for the error message.
        start = rendered.index("{")
        end = rendered.index("}", start)
        raise KeyError(f"feature_projection: unbound SQL placeholder {rendered[start : end + 1]!r}")
    return rendered


# The canonical registry. Order matches FeatureRow field declaration order so
# project_row can emit a tuple-positional FeatureRow construction below.
FEATURES: tuple[FeatureFormula, ...] = (
    # ----- Passthrough wallet aggregates -----
    FeatureFormula(
        name="prior_trades_count", dtype="int", nullable=False,
        py=lambda i: i.wallet.prior_trades_count,
        sql="{w.prior_trades_count}",
    ),
    FeatureFormula(
        name="prior_buys_count", dtype="int", nullable=False,
        py=lambda i: i.wallet.prior_buys_count,
        sql="{w.prior_buys_count}",
    ),
    FeatureFormula(
        name="prior_resolved_buys", dtype="int", nullable=False,
        py=lambda i: i.wallet.prior_resolved_buys,
        sql="{w.prior_resolved_buys}",
    ),
    FeatureFormula(
        name="prior_wins", dtype="int", nullable=False,
        py=lambda i: i.wallet.prior_wins,
        sql="{w.prior_wins}",
    ),
    FeatureFormula(
        name="prior_losses", dtype="int", nullable=False,
        py=lambda i: i.wallet.prior_losses,
        sql="{w.prior_losses}",
    ),
    FeatureFormula(
        name="prior_realized_pnl_usd", dtype="float", nullable=False,
        py=lambda i: i.wallet.realized_pnl_usd,
        sql="{w.realized_pnl_usd}",
    ),
    # prior_trades_30d: Python computes from recent_30d_trades deque;
    # DuckDB stage 2 pre-computes the count as wa.prior_trades_30d_w.
    FeatureFormula(
        name="prior_trades_30d", dtype="int", nullable=False,
        py=lambda i: sum(
            1
            for ts in i.wallet.recent_30d_trades
            if ts >= i.trade.ts - RECENT_TRADES_WINDOW_DAYS * SECONDS_PER_DAY
        ),
        sql="{w.prior_trades_30d}",
    ),
    # ----- Trade-row passthroughs -----
    FeatureFormula(
        name="bet_size_usd", dtype="float", nullable=False,
        py=lambda i: i.trade.notional_usd,
        sql="{t.notional_usd}",
    ),
    FeatureFormula(
        name="side", dtype="str", nullable=False,
        py=lambda i: i.trade.outcome_side,
        sql="{t.outcome_side}",
    ),
    FeatureFormula(
        name="implied_prob_at_buy", dtype="float", nullable=False,
        py=lambda i: i.trade.price,
        sql="{t.price}",
    ),
    # ----- Market-state passthroughs -----
    FeatureFormula(
        name="market_volume_so_far_usd", dtype="float", nullable=False,
        py=lambda i: i.market.volume_so_far_usd,
        sql="COALESCE({m.volume_so_far_usd}, 0.0)",
    ),
    FeatureFormula(
        name="market_unique_traders_so_far", dtype="int", nullable=False,
        py=lambda i: i.market.unique_traders_count,
        sql="CAST(COALESCE({m.unique_traders_count}, 0) AS INTEGER)",
    ),
    FeatureFormula(
        name="last_trade_price", dtype="float", nullable=True,
        py=lambda i: i.market.last_trade_price,
        sql="{m.last_trade_price}",
    ),
    # ----- Market metadata passthroughs -----
    FeatureFormula(
        name="market_category", dtype="str", nullable=False,
        py=lambda i: i.meta.category,
        sql="{meta.category}",
    ),
    # ----- Nullable divisions (denominator == 0 → None) -----
    FeatureFormula(
        name="win_rate", dtype="float", nullable=True,
        py=lambda i: (
            i.wallet.prior_wins / i.wallet.prior_resolved_buys
            if i.wallet.prior_resolved_buys > 0
            else None
        ),
        sql=(
            "CASE WHEN {w.prior_resolved_buys} > 0 "
            "THEN CAST({w.prior_wins} AS DOUBLE) / {w.prior_resolved_buys} "
            "ELSE NULL END"
        ),
    ),
    FeatureFormula(
        name="avg_implied_prob_paid", dtype="float", nullable=True,
        py=lambda i: (
            i.wallet.cumulative_buy_price_sum / i.wallet.cumulative_buy_count
            if i.wallet.cumulative_buy_count > 0
            else None
        ),
        sql=(
            "CASE WHEN {w.bet_size_count} > 0 "
            "THEN {w.cumulative_buy_price_sum} / {w.bet_size_count} "
            "ELSE NULL END"
        ),
    ),
    FeatureFormula(
        name="realized_edge_pp", dtype="float", nullable=True,
        py=lambda i: (
            (i.wallet.prior_wins / i.wallet.prior_resolved_buys)
            - (i.wallet.cumulative_buy_price_sum / i.wallet.cumulative_buy_count)
            if i.wallet.prior_resolved_buys > 0 and i.wallet.cumulative_buy_count > 0
            else None
        ),
        sql=(
            "CASE WHEN {w.prior_resolved_buys} > 0 AND {w.bet_size_count} > 0 "
            "THEN (CAST({w.prior_wins} AS DOUBLE) / {w.prior_resolved_buys}) "
            "- ({w.cumulative_buy_price_sum} / {w.bet_size_count}) "
            "ELSE NULL END"
        ),
    ),
    FeatureFormula(
        name="avg_bet_size_usd", dtype="float", nullable=True,
        py=lambda i: (
            i.wallet.bet_size_sum / i.wallet.bet_size_count
            if i.wallet.bet_size_count > 0
            else None
        ),
        sql=(
            "CASE WHEN {w.bet_size_count} > 0 "
            "THEN {w.bet_size_sum} / {w.bet_size_count} "
            "ELSE NULL END"
        ),
    ),
    FeatureFormula(
        name="median_bet_size_usd", dtype="float", nullable=True,
        # v1: not maintained — compute_features always emits None (features.py:389).
        py=lambda _i: None,
        sql="CAST(NULL AS DOUBLE)",
    ),
    FeatureFormula(
        name="bet_size_rel_to_avg", dtype="float", nullable=True,
        py=lambda i: (
            i.trade.notional_usd / (i.wallet.bet_size_sum / i.wallet.bet_size_count)
            if i.wallet.bet_size_count > 0 and i.wallet.bet_size_sum > 0
            else None
        ),
        sql=(
            "CASE WHEN {w.bet_size_count} > 0 AND {w.bet_size_sum} > 0 "
            "THEN {t.notional_usd} / ({w.bet_size_sum} / {w.bet_size_count}) "
            "ELSE NULL END"
        ),
    ),
    # ----- Wallet-quality interaction features (#44) -----
    FeatureFormula(
        name="edge_confidence_weighted", dtype="float", nullable=False,
        py=lambda i: (
            (
                (i.wallet.prior_wins / i.wallet.prior_resolved_buys)
                - (i.wallet.cumulative_buy_price_sum / i.wallet.cumulative_buy_count)
            )
            * min(1.0, i.wallet.prior_resolved_buys / CONFIDENCE_N_MIN)
            if i.wallet.prior_resolved_buys > 0 and i.wallet.cumulative_buy_count > 0
            else 0.0
        ),
        sql=(
            "CASE WHEN {w.prior_resolved_buys} > 0 AND {w.bet_size_count} > 0 "
            "THEN ((CAST({w.prior_wins} AS DOUBLE) / {w.prior_resolved_buys}) "
            "- ({w.cumulative_buy_price_sum} / {w.bet_size_count})) "
            f"* LEAST(1.0, CAST({{w.prior_resolved_buys}} AS DOUBLE) / {CONFIDENCE_N_MIN}.0) "
            "ELSE 0.0 END"
        ),
    ),
    FeatureFormula(
        name="win_rate_confidence_weighted", dtype="float", nullable=False,
        py=lambda i: (
            ((i.wallet.prior_wins / i.wallet.prior_resolved_buys) - 0.5)
            * min(1.0, i.wallet.prior_resolved_buys / CONFIDENCE_N_MIN)
            if i.wallet.prior_resolved_buys > 0
            else 0.0
        ),
        sql=(
            "CASE WHEN {w.prior_resolved_buys} > 0 "
            "THEN ((CAST({w.prior_wins} AS DOUBLE) / {w.prior_resolved_buys}) - 0.5) "
            f"* LEAST(1.0, CAST({{w.prior_resolved_buys}} AS DOUBLE) / {CONFIDENCE_N_MIN}.0) "
            "ELSE 0.0 END"
        ),
    ),
    FeatureFormula(
        name="is_high_quality_wallet", dtype="int", nullable=False,
        py=lambda i: int(
            i.wallet.prior_resolved_buys >= CONFIDENCE_N_MIN
            and i.wallet.prior_resolved_buys > 0
            and (i.wallet.prior_wins / i.wallet.prior_resolved_buys)
            > HIGH_QUALITY_WIN_RATE_THRESHOLD
        ),
        sql=(
            f"CASE WHEN {{w.prior_resolved_buys}} >= {CONFIDENCE_N_MIN} "
            "AND (CAST({w.prior_wins} AS DOUBLE) "
            f"/ NULLIF({{w.prior_resolved_buys}}, 0)) > {HIGH_QUALITY_WIN_RATE_THRESHOLD} "
            "THEN 1 ELSE 0 END"
        ),
    ),
    FeatureFormula(
        name="bet_size_relative_to_history", dtype="float", nullable=False,
        # v1: median_bet_size_usd is never maintained, so the ratio is
        # always 1.0. See features.py:389 + 399-401.
        py=lambda _i: 1.0,
        sql="CAST(1.0 AS DOUBLE)",
    ),
)


def project_row(
    *,
    trade: Trade,
    wallet: WalletState,
    market: MarketState,
    meta: MarketMetadata,
) -> FeatureRow:
    """Compute a FeatureRow from point-in-time state.

    Walks ``FEATURES``, evaluates each formula's ``py`` against
    ``FeatureInputs``, and packages the result into a FeatureRow.
    """
    inputs = FeatureInputs(wallet=wallet, market=market, meta=meta, trade=trade)
    values = {formula.name: formula.py(inputs) for formula in FEATURES}
    return FeatureRow(**values)  # type: ignore[arg-type]  # ty:ignore[invalid-argument-type]
